---
- name: Install Base packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_list }}"
    # - make
    # - build-essential 
    # - libssl-dev
    # - zlib1g-dev
    # - libbz2-dev
    # - libreadline-dev
    # - libsqlite3-dev
    # - wget
    # - curl
    # - llvm
    # - libncurses5-dev
    # - libncursesw5-dev
    # - xz-utils
    # - tk-dev
    # - libffi-dev
    # - liblzma-dev
    # - ca-certificates
    # - git
    # - tree
    # - zip
    # - unzip
    # - net-tools
    # - ffmpeg
    # - vim